- .travis.yml
- README.md
Successful build: https://travis-ci.org/zalando/go-keyring/builds/145776271
Close #2
> #2 Add travis integration for OSX

- .travis.yml
- README.md
This makes the tests run in a travis linux environment. It uses `python-gnomekeyring` to create the `'login'` keyring which is usually created by default on a normal desktop distro.
Fix #1
> #1 Run travis tests on linux

- README.md
- appveyor.yml
- keyring_test.go
- keyring_windows.go
* Adds Windows Credential Manager support by using the lib https://github.com/danieljoos/wincred
* Adds `appveyor.yml` config to run Windows tests on AppVeyor.
* Adds a missing test case to test deleting a non-existing secret.
Close #3
> Add Windows Credential Manager support

- keyring_linux.go
Getting a secret from the keyring would always fail on linux if the
keyring was locked. This patch fixes the issue by unlocking the keyring
before searching for the secret.
> linux: Unlock keyring on Get

- keyring.go
- keyring_linux.go
Makes the Keyring interface public such that it can be used by other
projects importing the library. Useful if you want to mock keyring access in tests.
> Make Keyring interface public

- secret_service/secret_service.go
Adds collection name to the error message so it's easier to debug.
Fix #14
> Add collection name to error message

- keyring_linux.go
- secret_service/secret_service.go
The object path `/org/freedesktop/secrets/collection/login` is not
necessarily available.
The D-Bus API reference from freedesktop.org specifies
`/org/freedesktop/secrets/aliases/default`, which is commonly used.
See: https://specifications.freedesktop.org/secret-service/ch12.html
This patch tries to accommodate both scenarios, by first checking whether
the direct path is available. If so it will be used as before, if not it
will fall back to the alias path.
> Fallback to default secret object path

- keyring_darwin.go
- keyring_test.go
Bugfix for multiline password encoding on OSX.  A workaround would be the feature development of certificate stores instead of password store types, but this fix is still worth having IMHO.
tl;dr is that OSX will hex encode passwords if there are certain characters in the stream, newlines are the one I stumbled upon. Gnome-keyring doesn't have this, so multiline passwords still come out un-encoded. I have not tested windows, but am hoping your CI will pick that up if work is needed so I don't have to install a vm :)
> add support for multiline passwords on all platforms

- keyring_darwin.go
- keyring_test.go
Fixes #36 
Adds a "well-known prefix" and hex encodes any incoming multiline string sent to `Set()`. Updates `Get()` to only decode when the well-known prefix is present.
**Warning:** This implementation will corrupt any existing multiline strings already in the keychain! On the plus side, it should un-corrupt any non-multiline strings that are currently being corrupted by #36.
Kudos to @jaroslaw-bochniak for the tests.
> Adding well-known prefix to encoded multiline strings

- go.mod
- go.sum
When I compiled my program that is using the go-keyring module, the following lines were added to my module's go.mod.
```
github.com/danieljoos/wincred v1.0.2 // indirect
github.com/godbus/dbus v4.1.0+incompatible // indirect
```
It is due to the absence of go.mod, and I'd like it to manage its own dependencies by itself.
> Adapted to Go 1.11 Modules

- secret_service/secret_service.go
When the default collection is opened the returned collection name is the actual name and not the alias. This happens when the collection is not named `login` and the default should be used.
> Fixes error when the default collection is opened.

- .github/workflows/go.yml
> Add GitHub Actions

- keyring_darwin.go
- keyring_test.go
OS X does return an hex encoded password at least on Big Sur
currently the test will fail, since no fix is implemented yet.
> Test umlaut passwords

- .github/workflows/go.yml
In github workflows:
- Bump golang version from `^1.15` to `^1.16` because `1.15` is no longer supported.
- Bump `ubuntu` to `latest` because `16.04` is removed.
Tested with the forked version: https://github.com/nhatthm/go-keyring/runs/3522332469?check_suite_focus=true
> Update github actions

- .github/workflows/go.yml
Add CI step for testing on FreeBSD. Uses https://github.com/marketplace/actions/freebsd-vm to run freebsd as github action.
Related to #67
> Add CI step for freebsd

- .github/workflows/go.yml
- keyring_unix.go
Ensure that it's possible to build for freebsd with cgo disabled.
Ref: https://github.com/zalando/go-keyring/issues/73
> Test building on freebsd with cgo disabled

- keyring.go
- keyring_darwin.go
- keyring_test.go
- keyring_windows.go
Using `Set` with too much data leads to errors and unknown behaviour on macos and windows.
This PR limits the passable data on those platforms to known limits. 
I also raised the max input on macos by switching to base64 for encoding. It uses a new prefix and also checks for the old one, so it should be backwards compatible.
This fixes #84
Also note that on macos the current behaviour actually interprets the input data as another command after a limit is reached. This could be a security vulnerability but is probably mitigated by the hex encoding.
> Limit set size

- secret_service/secret_service.go
Currently, when waiting for a prompt, it will block indefinitely unless the prompt sends back a **unicast** `Completed` signal, however that is not the standard. 
Though several do, such as gnome keyring, we cannot assume that all implementations of the Secret Service API will do this. 
For instance, KeepassXC is a popular password management tool that also implements the Secret Service and it uses a broadcast (destination field is null) message to signal back that a prompt has been completed or dismissed instead of a unicast message (direct to the original sender of the prompt). 
The discussion here is relevant: https://github.com/keepassxreboot/keepassxc/issues/7759 
The interesting points referenced there are [this documentation …
> Added support for prompt unlock broadcast rather than just unicast

- README.md
Drops Travis and Appvoyer badges from the README as we no longer use those systems for the build.
> Remove old CI badges no longer relevant

- secret_service/secret_service.go
Fixes https://github.com/zalando/go-keyring/issues/104
The current approach to handling prompts involves calling for a prompt and then registering a signal handler for a response that indicates the prompt had completed. In most cases, if the user were to take action, this would be quite slow. However, in the case of automatic responses to the prompt, the signal response may appear before the signal handler is configured, resulting in blocking forever.
This commit moves the call for a prompt after the signal handling has been configured, closing the race window.
I'll admit that I'm not very familiar with all the nuances of dbus or this library so it's entirely possible I've missed something. We've had three reports over on https://github.com/cli/cli/issues/8802 that this has resolved the …
> Fix suspected race condition in prompt handling

- secret_service/secret_service.go
Simple typo fix in `secret_service.go`.
> Fix typo in documentation

- keyring.go
- keyring_darwin.go
- keyring_fallback.go
- keyring_mock.go
- keyring_mock_test.go
- keyring_test.go
- keyring_unix.go
- keyring_windows.go
Possible implementation of #111
> feat: add DeleteAll methods to keyring

- README.md
Fixes #120 
This commit removes an extra trailing slash that was committed in #120. The existing link works, but it shouldn't end with two trailing slashes.
> fix(readme): remove extra trailing slash
